# 开发环境配置
server:
  # 服务器的HTTP端口
  port: 65534
  servlet:
    # 应用访问路径
    context-path: /
  tomcat:
    # Tomcat 的 URI 编码
    uri-encoding: UTF-8
    # 连接数满后的排队数
    accept-count: 1000
    threads:
      # Tomcat 最大线程数
      max: 800
      # Tomcat 启动初始化线程数
      min-spare: 100

# 日志配置
logging:
  level:
    # Spring 日志级别
    org.springframework: warn
    # 项目代码 日志级别
    cc.babysbreath: debug

# Spring 相关配置
spring:
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      enabled: true
      # 单文件最大
      max-file-size: 10MB
      # 总文件最大
      max-request-size: 100MB
  # redis配置
  redis:
    host: localhost
    port: 6379
    # 数据库索引
    database: 0
    password: wjc52292
    # 连接超时时间
    connect-timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# mybatis配置
mybatis:
  type-aliases-package: cc.babysbreath.domain
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30